version: '3.8'

services:
  db:
    container_name: postgresProductHistory
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=productHistory
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5456:5432"
