version: '3.8'

services:
  db:
    container_name: postgresProductPart
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5455:5432"
